name: Create release

on:
  push:
    tags:
    - '*'

jobs:
  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "Changelog: https://www.sphinx-doc.org/en/master/changes.html"
